### ISSUE TITLE
[Enhancement] Switch to using a single "Play/Pause" button

### ISSUE THREAD

**Issue by TheRogueArchivist** [aaru-dps/RedBookPlayer#13]
I think having a single button instead of 2 would be much more convenient, especially since there shouldn't be any use for pausing an already paused song, or playing an already playing one.

**Comment by mnadareski** [comment]
As of https://github.com/aaru-dps/RedBookPlayer/commit/49c0423b5d8746b05b0073af16f3a653757cf674, there's an event handler that can be hooked into by a theme to emulate a togglable play/pause button. I think that if that can be handled on a per-theme basis, it would be better than changing the default. If you're good with this, please close. Otherwise, comment and keep open.
